kind: Service 
apiVersion: v1
metadata:
  name: employee-management-postgres
  labels:
    name: employee-management-postgres
spec:
  ports:
    #- nodePort: 30163
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: employee-management-postgres
  #type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-postgres
spec:
  selector:
    matchLabels:
      app: employee-management-postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: employee-management-postgres
    spec:
      containers:
        - name: employee-management-postgres
          image: nandini15/employee-management-postgres
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password